### ISSUE TITLE
Adjust bug report template for severe bugs [improvement]

### ISSUE THREAD

**Issue by lshydro** [HydroSysPotsdam/Forester#50]
"_For bugs that prevent you from using Forester, please add the label 'severe'!_"
This is only possible for owners and contributors of the project. Please update the standard bug report template. I would suggest non-contributors reporting an issue can add the label to the title, e.g. [severe] or [improvement].

**Comment by david-strahl** [comment]
I implemented your suggestions and updated the bug report and feature request templates.
